version: '3.7'

services:
  neurodesktop:
    user: root
    privileged: true
    container_name: neurodesktop
    build:
      context: "."
      dockerfile: DockerfileUpdated
    volumes:
      - neurodesk-volume:/MES-CoBraD Input
      - 'C:/neurodesktop-storage:/neurodesktop-storage'
    ports:
      - '8080:8080'
#      - '8000:8000'
      - '8888:8888'
      - '4822:4822'
    environment:
      NEURODESKTOP_VERSION: 2024-01-12
    networks:
      - mri-freesurfer-network
    shm_size: 1gb


networks:
  mri-freesurfer-network:
    name: mri-freesurfer-network
    driver: bridge

volumes:
  neurodesk-volume:
    driver: local
    name: neurodesk-volume
