version: '3.7'

services:
  analytics-backend:
    build:
      context: "."
      dockerfile: ./Dockerfile
    hostname: analytics_backend
    container_name: analytics_backend
    restart: always
    environment:
      WFAddress: expertsystem_web_1
#    volumes:
#      - 'C:/neurodesktop-storage:/neurodesktop-storage'
    ports:
      - "7000:8000"
    networks:
      - mri-freesurfer-network
      - analytics-network

networks:
  analytics-network:
    name: analytics-network
    driver: bridge
  mri-freesurfer-network:
    name: mri-freesurfer-network
    driver: bridge
