version: '3.7'

services:
  nginx:
    build:
      context: "../nginx/"
      dockerfile: ./Dockerfile
    ports:
      - 85:80
      - 470:443
      - 472:444
      - 471:445
      - 473:446
      - 474:447
    depends_on:
      - analytics-backend
    networks:
      - mri-freesurfer-network
      - analytics-network

  neurodesktop:
    privileged: true
    container_name: neurodesktop
    build:
      context: "../docker_neurodesk/docker_neurodesk_production"
      dockerfile: Dockerfile
    volumes:
      - neurodesk-volume:/MES-CoBraD Input
      - '/home/ntua/neurodesktop-storage:/neurodesktop-storage'
    ports:
      - '8081:8080'
    networks:
      - mri-freesurfer-network
    shm_size: 1gb

  analytics-backend:
    build:
      context: "../../"
      dockerfile: ./docker/docker_production/Dockerfile
    hostname: analytics_backend
    container_name: analytics_backend
    restart: always
    environment:
      WFAddress: expertsystem_web_1
      NeurodesktopStorageLocation: /neurodesktop-storage
      NeurodesktopPort: 8081
      FrontendAddress: https://analytics.platform.mes-cobrad.eu
    volumes:
      - '/home/ntua/neurodesktop-storage:/neurodesktop-storage'
    ports:
      - "7000:8000"
    depends_on:
      - neurodesktop
    networks:
      - mri-freesurfer-network
      - analytics-network

networks:
  analytics-network:
    name: analytics-network
    driver: bridge
  mri-freesurfer-network:
    name: mri-freesurfer-network
    driver: bridge

volumes:
  neurodesk-volume:
    driver: local
    name: neurodesk-volume

#version: '3.7'
#
#services:
#  nginx:
#    build:
#      context: "../nginx/"
#      dockerfile: ./Dockerfile
#    ports:
#      - 80:80
#      - 443:443
#    depends_on:
#      - analytics-backend
#  analytics-backend:
#    build:
#      context: "../../"
#      dockerfile: ./docker/docker_production/Dockerfile
#    hostname: analytics_backend
#    container_name: analytics_backend
#    restart: always
#    environment:
#      WFAddress: expertsystem_web_1
#      NeurodesktopStorageLocation: /home/ntua/neurodesktop-storage
#      NeurodesktopPort: 8081
#      FrontendAddress: http://10.129.150.120:3005
#    volumes:
#      - '/home/ntua/neurodesktop-storage:/neurodesktop-storage'
#    ports:
#      - "7000:8000"
#    networks:
#      - mri-freesurfer-network
#      - analytics-network
#
#networks:
#  analytics-network:
#    name: analytics-network
#    driver: bridge
#  mri-freesurfer-network:
#    name: mri-freesurfer-network
#    driver: bridge
