FROM vnmd/neurodesktop:20220329
# De nomizo na xreiazetai license alla na xreiazete prepei na to fereis, trejto xoris kai me to xeri
#COPY license.txt /usr/local/freesurfer/.license

# Nomizo trexei kai me auto
#RUN apt-get update
#RUN apt-get install openssh-server

#Opos to proigoumeno
#RUN yum install openssh-server -y
#RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
#RUN echo "root:freesurferpwd" | chpasswd
#RUN ssh-keygen -A
#EXPOSE 22

CMD tail -f /dev/null
